variables:
#  DOCKER_DRIVER: overlay2                               # 用overlay2优化性能
  PROJECT_NAME: $CI_PROJECT_NAME                         # 用Gitlab工程名环境变量 打包的名字
  PROJECT_VERSION: "0.0.2"
  DOCKER_PRIX:  "mirrors.cloud.com:5000/app/"

stages:
  - build
  - deploy


npm-build:
  stage: build
  script:
    - npm -v
    - node -v
    - vue --version
    - npm config set registry https://registry.npm.taobao.org --global
    - npm config set disturl https://npm.taobao.org/dist --global
    - npm config  get cache
    - npm config get prefix
    - npm install
    - npm run build:prod
    - docker build -t $DOCKER_PRIX$PROJECT_NAME:$PROJECT_VERSION . # 生成docker镜像
    - docker push $DOCKER_PRIX$PROJECT_NAME:$PROJECT_VERSION       # 提交到镜像库
  artifacts:
    paths:
      - ./*.yaml    # 输出Deployment.yaml和Service.yaml供下一阶段的kubectl发布用

k8s-deploy:
  stage: deploy
  image:
    name: mirrors.com:5000/kubectl:1.14.2
    entrypoint: [""]                          # 覆盖原镜像的entrypoint，要不然会直接退出

  script:
    - kubectl apply -f Deployment.yaml        # 发布应用到k8s集群
    - kubectl set env deploy/arterycloud DEPLOY_DATE="$(date)"  # 让k8s强制更新镜像
